### ISSUE TITLE
Mark error cases more obviously

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/subiquity#110]
We already have color for the buttons (green).
We should mark error cases e.g. in red.

So when for example "ERROR: already mounted" shows up in the mask "Partition, format, and mount /dev/sda" we could not only show it but make it red until the user enters something new in there.

Also we could store a status along that until the user enters something new there (removes the red) we will not accept the input.

**Comment by cyphermox** [comment]
Mirrored to LP: https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1642651
