### ISSUE TITLE
missing dependency to cloud-image-utils

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/subiquity#131]
I'm testing on a pristine xenial and found one more dependency missing for image based testing.

The failure is rather readable (thanks for that!)
- echo '1452252540: Converting mass ephemeral image to roottar'
  1452252540: Converting mass ephemeral image to roottar
- '[' '!' -r /home/paelzer/download/maas/daily/wily/amd64/20160106/root.tar.gz ']'
- /home/paelzer/download/curtin/tools/maas2roottar /home/paelzer/download/maas/daily/wily/amd64/20160106/root-image.gz /home/paelzer/download/maas/daily/wily/amd64/20160106/root.tar.gz
  no mount-image-callback. install cloud-image-utils.
- '[' 1 '!=' 0 ']'
- log 'ERROR: Failed to convert ephemeral to roottar'
- tee -a geninstaller.log
  ++ date +%s
- echo '1452252540: ERROR: Failed to convert ephemeral to roottar'
  1452252540: ERROR: Failed to convert ephemeral to roottar

Fix should be easy as well, make "cloud-image-utils" a dependency that is installed on install_deps.

**Comment by cyphermox** [comment]
Mirrored to LP: https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1642646
