### ISSUE TITLE
Provide a way to get the MAC address

### ISSUE THREAD

**Issue by warsaw** [CanonicalLtd/subiquity#177]
There are lots of reasons why the MAC may be needed before you can configure the networking on the device.  For example, you might have to set up DHCP or enable access via your router.

**Comment by mwhudson** [comment]
I don't understand, the MAC address is already displayed?

![mac_address](https://cloud.githubusercontent.com/assets/672022/19743085/42e05dd6-9c24-11e6-8cc1-7fc610837076.png)

**Comment by warsaw** [comment]
On Oct 26, 2016, at 01:04 PM, Michael Hudson-Doyle wrote:

>I don't understand, the MAC address is already displayed?

I don't see that when I boot the BeagleBoardBlack, but it could be because of
a NIC related kernel oops.  I'll check again once that bug is fixed.

**Comment by cyphermox** [comment]
Mirrored to LP: https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1642645
