### ISSUE TITLE
Manpages missing, --help on subiquity-runinstaller dangerous

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/subiquity#66]
It might just be too early for manpages, so so that is ok (for now) :-)

Three of the tools have at least a --help text - good.
But subiquity-runinstaller ignores this completely.

No help, No "unknown option" it starts to do something right away - which could be dangerous.

Basic - but still a bug - example:

> subiquity-runinstaller --help
> Installing required packages: ovmf qemu-system-x86
> Reading package lists... Done
> Building dependency tree  
> Reading state information... Done
> The following extra packages will be installed:
> [...]

**Comment by cyphermox** [comment]
Mirrored to LP: https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1642660
