### ISSUE TITLE
Navigation improvement

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/subiquity#68]
A)
In all Menus provide shortcuts for the menu entries.
Like when having "Done" and "Cancel" mark a Character like "D" and "C" and allow users to shortcut with e.g. ALT+C ALT+D

A bit like it is done in Suse yast.
It is suppores to be a fast and slim installer, so tihs makes it faster.

Especially in longer lists this is the only way to get to e.g. cancel.
So if for example the initial language List would be way longer to get to cancel 

B)
Masks which take input fields should "go to the next field" on enter.
So e.g. in the user config one has to enter:
Real Name -> then go down -> Username -> then go down -> ...
Users would expect that this works as well (just faster in the fingers, since they are used to)
Real Name -> enter -> Username -> enter -> ...

C)
In longer lists it would be great if there would be a wrap around so that going "up" from the topmost item would warp you to the last entry (or the menu buttons below whichever applies)

D) You did a great job simplifying things.
But the language selection could still be optimized.
Eventually you have to start with some language anyway.
So far you choose english.
There has to be no menu.
If you implment A) in this bug you could on all panels provide a "change Langauge" button so a user can change.
Since most users would rely on just one language which is english anyway they have "saved" one menu to select from.
I guess starting from the currents system default language by default would be great.
On top you could provide a commandline switch for the language - in case someone doesn't understand anything at all - but that switch is probably overengineering.

**Comment by cyphermox** [comment]
Mirrored/moved to Launchpad: https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1642664
