### ISSUE TITLE
UI - Scaling min/max

### ISSUE THREAD

**Issue by cpaelzer** [CanonicalLtd/subiquity#79]
A)
There is a certain minimum console size requirement.
I tried it on  a 12x8 console and - obviously - it wasn't usable in any way.
We should add a check for this and gracefully exit if the console is unsuitably small.

For the case that we don't get any console info we should try going on - as there might be enough weird ones which still work.
But if it is known to be too small - I'd say we should exit gracefully.

B)
Also if a console is really huge it can get ugly.
The scaling is nice, but this flexibility makes UI testing hard.
The only thing that really grows is the progress bar, everything else is just characters.
So why not defining some upper limit like classic 80x40 console or 172x41 which seems common for a full-hd screen in default resolution.
If now the current console is way bigger just take the upper-left + max console size and leave the rest blank.
This would avoid some hard to test max scaling issues.

**Comment by cyphermox** [comment]
Mirrored to LP: https://bugs.launchpad.net/ubuntu/+source/subiquity/+bug/1642655
